version: "3.7"

services:

  web:
    build: "./app"
    container_name: ${DJANGO_CONTAINER_NAME}
    restart: "always"
    expose:
      - "8000"
    volumes:
      - ./volumes/app:/home/appuser/app
      - ./volumes/log:/home/appuser/log
    networks:
      - web_network
      - nginx_network
      - redis_network
      - minio_network
    env_file:
      - "./.env"
    depends_on:
      - "redis"
      - "postgres"
      - "minio"
    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres:alpine
    container_name: ${POSTGRES_CONTAINER_NAME}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres_network
    volumes:
      - ./volumes/db:/var/lib/postgresql/data 
    security_opt:
      - no-new-privileges:true

  minio: 
    image: quay.io/minio/minio
    container_name: ${MINIO_CONTAINER_NAME}
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio_network
    environment:
      MINIO_ROOT_USER: ${DJANGO_MINIO_STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${DJANGO_MINIO_STORAGE_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:alpine
    container_name: ${REDIS_CONTAINER_NAME}
    command: redis-server --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    restart: always
    volumes: 
      - ./volumes/redis/data:/data
    networks:
      - redis_network
    security_opt:
      - no-new-privileges:true

  nginx:
    build: "./nginx"
    container_name: ${NGINX_CONTAINER_NAME}
    restart: "always"
    ports:
      - ${NGINX_PORT}:80
    networks:
      - nginx_network
    depends_on:
      - "web"
    volumes:
      - ./volumes/log:/var/log/nginx
    security_opt:
      - no-new-privileges:true

volumes:
  redis:
    driver: local

networks:
  web_network:
    # external: True
  postgres_network:
    # external: True
  minio_network:
    # external: True
  redis_network:
    # external: True
  nginx_network:
    # external: True
